# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\desktop2\projects\pyqt5\Minecraft_Auto_Commands\g.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MinecraftAutoCommand(object):
    def setupUi(self, MinecraftAutoCommand):
        MinecraftAutoCommand.setObjectName("MinecraftAutoCommand")
        MinecraftAutoCommand.resize(563, 608)
        self.centralwidget = QtWidgets.QWidget(MinecraftAutoCommand)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nothing = QtWidgets.QFrame(self.centralwidget)
        self.nothing.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.nothing.setStyleSheet("QPushButton {\n"
"border: none;\n"
"padding: 5px 10px;\n"
"background-color: #f7f7f7;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"QFrame {\n"
"border-top-right-radius: 5px;\n"
"border-top-left-radius: 5px;\n"
"    background-color: rgb(83, 83, 83);\n"
"}")
        self.nothing.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nothing.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nothing.setObjectName("nothing")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.nothing)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dragFrame = QtWidgets.QFrame(self.nothing)
        self.dragFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dragFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dragFrame.setObjectName("dragFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.dragFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.dragFrame)
        self.label.setStyleSheet("\n"
"color: gray;\n"
"image: url(:/newPrefix/images/logo.png);\n"
"font-weight:bold;\n"
"padding: 4px;\n"
"min-width: 20px;\n"
"margin-left:5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.dragFrame)
        self.label_3.setStyleSheet("font-weight:bold;\n"
"color: lightgray;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.dragFrame)
        self.minimize = QtWidgets.QPushButton(self.nothing)
        self.minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize.setStyleSheet("\n"
"QPushButton {\n"
"image: url(:/newPrefix/images/24x24/cil-window-minimize.png);\n"
"\n"
"background-color: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #666666;\n"
"}")
        self.minimize.setText("")
        self.minimize.setObjectName("minimize")
        self.horizontalLayout.addWidget(self.minimize)
        self.close = QtWidgets.QPushButton(self.nothing)
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.close.setStyleSheet("\n"
"QPushButton {\n"
"    image: url(:/newPrefix/images/20x20/cil-x.png);\n"
"    background-color: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: tomato;\n"
"}")
        self.close.setText("")
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addWidget(self.nothing)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("border-bottom-right-radius: 5px;\n"
"border-bottom-left-radius: 5px;\n"
"background-color: rgb(102, 102, 102);\n"
"font-size:16px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.frame_12)
        self.frame_7.setStyleSheet("QFrame {\n"
"background-color: #727272;\n"
"color: #fff;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border-radius: 5px;\n"
"    color: #fff;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.hotkeyEdit = QtWidgets.QLineEdit(self.frame_8)
        self.hotkeyEdit.setObjectName("hotkeyEdit")
        self.verticalLayout_5.addWidget(self.hotkeyEdit)
        self.horizontalLayout_8.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.cmdEdit = QtWidgets.QLineEdit(self.frame_10)
        self.cmdEdit.setObjectName("cmdEdit")
        self.verticalLayout_7.addWidget(self.cmdEdit)
        self.horizontalLayout_8.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.addBtn = QtWidgets.QPushButton(self.frame_9)
        self.addBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBtn.setStyleSheet("QPushButton {\n"
"color: #fff;\n"
"background-color: #84c184;\n"
"padding: 5px;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #66b266;\n"
"}")
        self.addBtn.setObjectName("addBtn")
        self.verticalLayout_9.addWidget(self.addBtn)
        self.horizontalLayout_8.addWidget(self.frame_9)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_8.setStretch(1, 100)
        self.horizontalLayout_9.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setStyleSheet("color: #fff;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.AutoClicker = QtWidgets.QWidget()
        self.AutoClicker.setObjectName("AutoClicker")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.AutoClicker)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.AutoClicker)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_13 = QtWidgets.QFrame(self.frame_6)
        self.frame_13.setStyleSheet("QFrame {\n"
"background-color: #727272;\n"
"color: #fff;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_23 = QtWidgets.QFrame(self.frame_13)
        self.frame_23.setStyleSheet("QFrame {\n"
"background-color: #727272;\n"
"color: #fff;\n"
"border-radius: 3px;\n"
"}\n"
"QRadioButton {\n"
"background-color: none;\n"
"}\n"
"")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_7.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_22 = QtWidgets.QFrame(self.frame_23)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.frame_22)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pressEnter = QtWidgets.QCheckBox(self.frame_5)
        self.pressEnter.setStyleSheet("background-color: none;")
        self.pressEnter.setChecked(True)
        self.pressEnter.setObjectName("pressEnter")
        self.verticalLayout_4.addWidget(self.pressEnter)
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setStyleSheet("background-color: rgb(255, 201, 14);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        # font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-size: 10px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.emergencyKey = QtWidgets.QLineEdit(self.frame)
        self.emergencyKey.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.emergencyKey.setStyleSheet("QLineEdit {\n"
"    border-radius: 5px;\n"
"    color: #fff;\n"
"    background-color: rgb(255, 216, 79);\n"
"    padding: 5px;\n"
"}\n"
"")
        self.emergencyKey.setObjectName("emergencyKey")
        self.horizontalLayout_2.addWidget(self.emergencyKey, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.frame)
        self.textEdit = QtWidgets.QTextEdit(self.frame_5)
        self.textEdit.setEnabled(True)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.frame_34 = QtWidgets.QFrame(self.frame_22)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.stopBtn = QtWidgets.QPushButton(self.frame_34)
        self.stopBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopBtn.setStyleSheet("QPushButton {\n"
"    image: url(:/newPrefix/images/24x24/cil-media-stop.png);\n"
"background-color:#ff6f6f;\n"
"padding:5px;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#ff4c4c;\n"
"}")
        self.stopBtn.setText("")
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_12.addWidget(self.stopBtn)
        self.startBtn = QtWidgets.QPushButton(self.frame_34)
        self.startBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startBtn.setStyleSheet("QPushButton {\n"
"image: url(:/newPrefix/images/24x24/cil-media-play.png);\n"
"background-color: #84c184;\n"
"padding: 5px;\n"
"border-radius: 3px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #66b266;\n"
"}")
        self.startBtn.setText("")
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout_12.addWidget(self.startBtn)
        self.verticalLayout_8.addWidget(self.frame_34)
        self.horizontalLayout_7.addWidget(self.frame_22)
        self.frame_19 = QtWidgets.QFrame(self.frame_23)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_40 = QtWidgets.QFrame(self.frame_19)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_40)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.eventLogLabel = QtWidgets.QLabel(self.frame_40)
        self.eventLogLabel.setStyleSheet("color: lightgray;")
        self.eventLogLabel.setObjectName("eventLogLabel")
        self.horizontalLayout_10.addWidget(self.eventLogLabel)
        self.lastUpdate = QtWidgets.QLabel(self.frame_40)
        self.lastUpdate.setStyleSheet("font-size: 10px;\n"
"color: lightgray;")
        self.lastUpdate.setObjectName("lastUpdate")
        self.horizontalLayout_10.addWidget(self.lastUpdate, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_15.addWidget(self.frame_40)
        self.log = QtWidgets.QListWidget(self.frame_19)
        font = QtGui.QFont()
        # font.setPointSize(-1)
        self.log.setFont(font)
        self.log.setStyleSheet("background-color: rgba(148, 148, 148, 102);\n"
"border-radius:3px;\n"
"padding:5px;\n"
"font-size: 14px;")
        self.log.setObjectName("log")
        self.verticalLayout_15.addWidget(self.log)
        self.verticalLayout_15.setStretch(1, 1)
        self.horizontalLayout_7.addWidget(self.frame_19)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 5)
        self.verticalLayout_11.addWidget(self.frame_23)
        self.horizontalLayout_6.addWidget(self.frame_13)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.stackedWidget.addWidget(self.AutoClicker)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_11 = QtWidgets.QFrame(self.frame_2)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2.addWidget(self.frame_11)
        self.verticalLayout.addWidget(self.frame_2)
        MinecraftAutoCommand.setCentralWidget(self.centralwidget)

        self.retranslateUi(MinecraftAutoCommand)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MinecraftAutoCommand)

    def retranslateUi(self, MinecraftAutoCommand):
        _translate = QtCore.QCoreApplication.translate
        MinecraftAutoCommand.setWindowTitle(_translate("MinecraftAutoCommand", "Minecraft Auto Command"))
        self.label_3.setText(_translate("MinecraftAutoCommand", "Minecraft Auto Command"))
        self.label_4.setText(_translate("MinecraftAutoCommand", "Hot key (Any character)"))
        self.label_5.setText(_translate("MinecraftAutoCommand", "Command (e.g. /home)"))
        self.addBtn.setText(_translate("MinecraftAutoCommand", "  Add  "))
        self.pressEnter.setText(_translate("MinecraftAutoCommand", "\'Enter\' after command input"))
        self.label_2.setText(_translate("MinecraftAutoCommand", "Emergency exit hot key"))
        self.emergencyKey.setText(_translate("MinecraftAutoCommand", "]"))
        self.textEdit.setHtml(_translate("MinecraftAutoCommand", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">INSTRUCTIONS:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1. </span><span style=\" font-size:9pt; font-weight:600;\">Enter hot key</span><span style=\" font-size:9pt;\"> </span><span style=\" font-size:9pt; font-style:italic;\">(this can be any keyboard character)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-style:italic;\">This key can be clicked anytime during game play.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-style:italic;\">Examples: shift + w, ctrl + c, [, 7</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-style:italic;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2.</span><span style=\" font-size:9pt; font-weight:600;\"> Enter command</span><span style=\" font-size:9pt;\"> (this can be any working command)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Examples: /home, /wild, /spawn, /sethome, /msg &lt;user_name&gt;</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3. </span><span style=\" font-size:9pt; font-weight:600;\">Click \'Add\' button </span><span style=\" font-size:9pt; font-style:italic;\">(this will stop the app)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Optional: </span><span style=\" font-size:9pt;\">Enter after command input. The default is set to True</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Optional: </span><span style=\" font-size:9pt;\">Enter emergency hot key. The default is set to ]</span></p></body></html>"))
        self.stopBtn.setToolTip(_translate("MinecraftAutoCommand", "Stop Hot Key Recognition!"))
        self.startBtn.setToolTip(_translate("MinecraftAutoCommand", "Start Hot Key Recognition!"))
        self.eventLogLabel.setText(_translate("MinecraftAutoCommand", "Event Log"))
        self.lastUpdate.setText(_translate("MinecraftAutoCommand", "            00:00:00 am"))
import resources_rc
